spring.application.name: spring-docker-test

server:
  port: 8080

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health # "*" 로 모두 노출 가능, 어떤 기능이 있는지 추후 확인 필요
  endpoint:
    health:
      show-details: always # (never, always, when_authorized), debug 용도로 always 사용 할 시 편함
